### ISSUE TITLE
Line 28, the id should be 'currencies-all'

### ISSUE THREAD

**Issue by cool007zqw** [bradlucas/coinmarketcap#1]
Coinmarketcap seems to have merged assets category with currencies.

so in line 28
'assets-all' needs to be replaced by 'currencies-all'

**Comment by bradlucas** [comment]
Hi,
Thanks for pointing this out. I appreciate it.

I went and checked out your suggestion and do see the table having a new id. I tried the change but noticed the script breaks not because of the suggested change but because the table has changed columns as well.

I now notice that https://coinmarketcap.com/assets/views/all/ no longer includes the platform column which is needed.

In poking around it now looks like the page originally used to develop the script is now at https://coinmarketcap.com/tokens/views/all/

Changing the script to use that url now causes it to work as before.

I've updated the repo. 

Please let me know if it works for you or if you have other suggestions.

And again, thanks very much for pointing this out.

- Brad
